### ISSUE TITLE
Primal core issue 

### ISSUE THREAD

**Issue by StephJ2Fan** [Jasondia16/AlIinOne#3]
[latest.log](https://github.com/Jasondia16/AlIinOne/files/2452488/latest.log)
Version Stable 04

**Comment by Jasondia16** [comment]
k i'll notify the Authors of Primal Core Thanks

**Comment by An-Sar** [comment]
@StephJ2Fan are you able to reliably reproduce this crash? also can you put your Betweenlands config up on pastebin or something similar?

**Comment by StephJ2Fan** [comment]
I can reliably reproduce this crash, and let me get you the config.

**Comment by StephJ2Fan** [comment]
[config.txt](https://github.com/Jasondia16/AlIinOne/files/2453366/config.txt)
I had to save it as a txt file to upload to Github, @An-Sar

**Comment by An-Sar** [comment]
i cannot recreate this crash, but i have deployed a possible fix there is a [dev build available](https://www.dropbox.com/s/h2c84db4tglwcvo/PrimalCore-1.12.2-0.6.94.1.jar), if you are able to give it a test and report back it would be a great help.

**Comment by StephJ2Fan** [comment]
Alright @An-Sar I've updated it, and I will test it out probably tomorrow night after I get done with my weekend tasks.

**Comment by Jasondia16** [comment]
It appears That you released The Fix @An-Sar So does it mean tht th issue is done? (Resolved)

**Comment by An-Sar** [comment]
i believe so, someone else ran into the same issue and the fix worked for them.
